export type GalleryImage = {
  src: string
  alt: string
  category: 'interior' | 'exterior' | 'surroundings'
  featured: boolean
}

export const galleryImagesByLodge: Record<string, GalleryImage[]> = {
  lodge1: [
    // Glenridding Lodge
    { src: '/Glenridding/1.jpeg', alt: 'Glenridding exterior', category: 'exterior', featured: true },
    { src: '/Glenridding/interior (2).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (3).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (4).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (5).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (6).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (7).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (8).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (9).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (10).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (11).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (12).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (13).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (14).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (15).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (16).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (17).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (18).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (19).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (20).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (21).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (22).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (23).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (24).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (25).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (26).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (27).jpeg', alt: 'Glenridding interior', category: 'interior', featured: true },
    { src: '/Glenridding/interior (28).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (29).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (30).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (31).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/interior (32).jpeg', alt: 'Glenridding interior', category: 'interior', featured: false },
    { src: '/Glenridding/pool.jpeg', alt: 'Glenridding interior', category: 'interior', featured: true },
    { src: '/Glenridding/exterior.jpeg', alt: 'Glenridding exterior', category: 'exterior', featured: false },
    { src: '/Glenridding/exterior (1).jpeg', alt: 'Glenridding exterior', category: 'exterior', featured: false },
    { src: '/Glenridding/exterior (2).jpeg', alt: 'Glenridding exterior', category: 'exterior', featured: true },
    { src: '/Glenridding/exterior (3).jpeg', alt: 'Glenridding exterior', category: 'exterior', featured: false },
    { src: '/Glenridding/surroundings (1).jpeg', alt: 'Glenridding surroundings', category: 'surroundings', featured: true },
    { src: '/Glenridding/surroundings (2).jpeg', alt: 'Glenridding surroundings', category: 'surroundings', featured: true },
    { src: '/Glenridding/surroundings (3).jpeg', alt: 'Glenridding surroundings', category: 'surroundings', featured: false },
  ],
  lodge2: [
    // Water's Reach
    { src: '/Waters_Reach/1.jpeg', alt: "Water's Reach interior", category: 'interior', featured: true },
    { src: '/Waters_Reach/interior (1).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (2).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (3).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (4).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (5).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (6).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (7).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (8).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (9).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (10).jpeg', alt: "Water's Reach interior", category: 'interior', featured: true },
    { src: '/Waters_Reach/interior (11).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (12).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (13).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (14).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (15).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (16).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (17).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (18).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (19).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (20).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/interior (21).jpeg', alt: "Water's Reach interior", category: 'interior', featured: false },
    { src: '/Waters_Reach/pool.jpeg', alt: "Water's Reach exterior", category: 'interior', featured: false },
    { src: '/Waters_Reach/gym (1).jpeg', alt: "Water's Reach exterior", category: 'interior', featured: false },
    { src: '/Waters_Reach/gym (2).jpeg', alt: "Water's Reach exterior", category: 'interior', featured: false },
    { src: '/Waters_Reach/zumba.jpeg', alt: "Water's Reach exterior", category: 'interior', featured: false },
    { src: '/Waters_Reach/exterior (1).png', alt: "Water's Reach exterior", category: 'exterior', featured: true },
    { src: '/Waters_Reach/exterior (2).jpeg', alt: "Water's Reach exterior", category: 'exterior', featured: false },
    { src: '/Waters_Reach/exterior (3).jpeg', alt: "Water's Reach exterior", category: 'exterior', featured: false },
    { src: '/Waters_Reach/exterior (4).jpeg', alt: "Water's Reach exterior", category: 'exterior', featured: false },
    { src: '/Waters_Reach/exterior (5).jpeg', alt: "Water's Reach exterior", category: 'exterior', featured: false },
    { src: '/Waters_Reach/exterior (6).jpeg', alt: "Water's Reach exterior", category: 'exterior', featured: false },
    { src: '/Waters_Reach/exterior (7).jpeg', alt: "Water's Reach exterior", category: 'exterior', featured: false },
    { src: '/Waters_Reach/exterior (8).jpeg', alt: "Water's Reach exterior", category: 'exterior', featured: false },
    { src: '/Waters_Reach/exterior (9).jpeg', alt: "Water's Reach exterior", category: 'exterior', featured: false },
    { src: '/Waters_Reach/exterior (10).jpeg', alt: "Water's Reach exterior", category: 'exterior', featured: false },
    { src: '/Waters_Reach/surroundings (1).jpeg', alt: "Water's Reach surroundings", category: 'surroundings', featured: false },
    { src: '/Waters_Reach/surroundings (2).jpeg', alt: "Water's Reach surroundings", category: 'surroundings', featured: false },
    { src: '/Waters_Reach/surroundings (3).jpeg', alt: "Water's Reach surroundings", category: 'surroundings', featured: false },
  ],
  lodge3: [
    // Serenity
    { src: '/Serenity/1.png', alt: 'Serenity interior', category: 'interior', featured: true },
    { src: '/Serenity/interior (1).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (2).jpg', alt: 'Serenity interior', category: 'interior', featured: true },
    { src: '/Serenity/interior (3).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (4).jpg', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (5).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (6).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (7).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (8).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (9).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (10).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (11).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (12).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (13).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (14).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (15).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (16).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (17).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (18).jpg', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (19).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/interior (20).png', alt: 'Serenity interior', category: 'interior', featured: false },
    { src: '/Serenity/exterior (1).png', alt: 'Serenity exterior', category: 'exterior', featured: true },
    { src: '/Serenity/exterior (2).png', alt: 'Serenity exterior', category: 'exterior', featured: false },
    { src: '/Serenity/exterior (3).png', alt: 'Serenity exterior', category: 'exterior', featured: false },
    { src: '/Serenity/exterior (4).png', alt: 'Serenity exterior', category: 'exterior', featured: false },
    { src: '/Serenity/exterior (5).png', alt: 'Serenity exterior', category: 'exterior', featured: false },
    { src: '/Serenity/exterior (6).png', alt: 'Serenity exterior', category: 'exterior', featured: false },
    { src: '/Serenity/exterior (7).png', alt: 'Serenity exterior', category: 'exterior', featured: false },
    { src: '/Serenity/exterior (8).png', alt: 'Serenity exterior', category: 'exterior', featured: false },
    { src: '/Serenity/surroundings (1).png', alt: 'Serenity surroundings', category: 'surroundings', featured: true },
    { src: '/Serenity/surroundings (2).png', alt: 'Serenity surroundings', category: 'surroundings', featured: true },
  ],
} 